---
apiVersion: v1
kind: Service
metadata:
  name: "{{ Values.resource.component }}-headless-service"
  namespace: "{{ Values.project.namespace }}"
spec:
  clusterIP: None
  selector:
    project: "{{ Values.project.name }}"
    component: "{{ Values.resource.component }}"
  ports:
    - protocol: TCP
      port: "{{ Values.service.port }}"
      targetPort: "{{ Values.service.targetPort }}"

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ Values.resource.component }}-service"
  namespace: "{{ Values.project.namespace }}"
spec:
  selector:
    project: "{{ Values.project.name }}"
    component: "{{ Values.resource.component }}"
  ports:
    - protocol: TCP
      port: "{{ Values.service.port }}"
      targetPort: "{{ Values.service.targetPort }}"
