apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.resource.name }}"
  namespace: expense
spec:
  selector:
    matchLabels:
      project: "{{ .Values.project.name }}"
      component: "{{ .Values.resource.component }}"
  serviceName: "{{ .Values.resource.component }}-headless-service"
  replicas: {{ .Values.resource.replicas }}
  template:
    metadata:
      labels:
        project: "{{ .Values.project.name }}"
        component: "{{ .Values.resource.component }}"
    spec:
      containers:
      - name: "{{ .Values.resource.name }}"
        image: "joindevops/{{ .Values.resource.name }}:v1.0"
        volumeMounts:
        - name: "{{ .Values.resource.name }}"
          mountPath: "/var/lib/{{ .Values.resource.name }}"
  volumeClaimTemplates:
  - metadata:
      name: "{{ .Values.resource.name }}" # Must match volumeMounts.name
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
