apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  labels:
    project: "{{ .Values.project.name }}"
    component: storageclass
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
