apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: expense
data:
  DB_HOST: db-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: expense
  labels:
    project: expense
    component: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: backend
  template:
    metadata:
      labels:
        project: expense
        component: backend
    spec:
      containers:
        - name: nginx
          image: joindevops/backend:v1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense
spec:
  selector:
    project: expense
    component: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
