apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.resource.component }}-deployment"
  namespace: "{{ .Values.project.namespace }}"
  labels:
    project: "{{ .Values.project.name }}"
    component: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      project: "{{ .Values.project.name }}"
      component: "{{ .Values.resource.component }}"
  template:
    metadata:
      labels:
        project: "{{ .Values.project.name }}"
        component: "{{ .Values.resource.component }}"
    spec:
      containers:
        - name: nginx
          image: "joindevops/{{ .Values.resource.component }}:v1.0"
          envFrom:
            - configMapRef:
                name: "{{ .Values.resource.component }}-configmap"